# Generated by Django 3.2.20 on 2024-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_display_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='restrict_view',
            field=models.BooleanField(default=False, help_text='This course will be displayed in to all users', verbose_name='View Restriction'),
        ),
    ]
