# Generated by Django 3.2.20 on 2024-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_course_restrict_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='restrict_view',
            field=models.BooleanField(default=False, help_text='This course is restricted and can only be viewed by myself.', verbose_name='View Restriction'),
        ),
    ]
