# Generated by Django 3.2.20 on 2024-01-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_course_restrict_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='restrict_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.viewrestriction', verbose_name='View Restriction'),
        ),
    ]
