# Generated by Django 3.2.20 on 2024-01-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20240119_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewrestriction',
            options={'verbose_name': 'View Restriction'},
        ),
        migrations.RemoveField(
            model_name='viewrestriction',
            name='name',
        ),
        migrations.AddField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PV', 'Private'), ('PU', 'Public'), ('ST', 'Student Only')], default='PU', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='restrict_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='base.viewrestriction', verbose_name='View Restriction'),
        ),
    ]
