# Generated by Django 3.2.20 on 2024-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20240119_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewrestriction',
            options={'ordering': ['restriction'], 'verbose_name': 'View Restriction'},
        ),
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PV', 'Private'), ('ST', 'Student Only'), ('PU', 'Public')], default='PU', max_length=150),
        ),
    ]
