# Generated by Django 3.2.20 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_viewrestriction_restriction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewrestriction',
            options={'ordering': ['restriction'], 'verbose_name': 'View Restriction'},
        ),
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PU', 'Public'), ('ST', 'Student Only'), ('PV', 'Private')], default='PU', max_length=150),
        ),
    ]
