# Generated by Django 3.2.20 on 2024-01-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20240126_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PV', 'Private'), ('PU', 'Public'), ('ST', 'Student Only')], default='PU', max_length=150),
        ),
    ]
