# Generated by Django 3.2.20 on 2024-01-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_viewrestriction_restriction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewrestriction',
            options={'ordering': ['restriction'], 'verbose_name': 'View Restriction', 'verbose_name_plural': 'Restrictions'},
        ),
    ]
