# Generated by Django 3.2.20 on 2024-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_viewrestriction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PV', 'Private'), ('ST', 'Student Only'), ('PU', 'Public')], default='PU', max_length=150),
        ),
    ]
