# Generated by Django 3.2.20 on 2024-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_viewrestriction_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('PU', 'Public'), ('PV', 'Private'), ('ST', 'Student Only')], default='PU', max_length=150),
        ),
    ]
