# Generated by Django 3.2.20 on 2024-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_viewrestriction_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('ST', 'Student Only'), ('PU', 'Public'), ('PV', 'Private')], default='PU', max_length=150),
        ),
    ]
