# Generated by Django 3.2.20 on 2024-02-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_viewrestriction_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrestriction',
            name='restriction',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Student Only', 'Student Only')], default='Public', max_length=150),
        ),
    ]
